"""add source and status to topics

Revision ID: 7f67e9ee8883
Revises: 
Create Date: 2026-01-15 19:39:57.539612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f67e9ee8883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brand_mutation_logs_id'), table_name='brand_mutation_logs')
    op.drop_table('brand_mutation_logs')
    op.drop_index(op.f('ix_engagement_logs_id'), table_name='engagement_logs')
    op.drop_table('engagement_logs')
    op.drop_index(op.f('ix_generated_contents_id'), table_name='generated_contents')
    op.drop_table('generated_contents')
    op.drop_table('linkedin_tokens')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_prompt_performance_logs_id'), table_name='prompt_performance_logs')
    op.drop_table('prompt_performance_logs')
    op.alter_column('approval_batches', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('brand_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('brand_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('content_items', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('content_items', sa.Column('content_text', sa.Text(), nullable=True))
    op.add_column('content_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('content_items', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('content_items', 'platform',
               existing_type=postgresql.ENUM('linkedin', 'instagram', 'facebook', name='platform_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('content_items', 'content_type',
               existing_type=postgresql.ENUM('text', 'image', 'reel', 'carousel', name='content_type_enum'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('content_items', 'status',
               existing_type=postgresql.ENUM('draft', 'generated', 'pending_approval', 'approved', 'scheduled', 'published', 'failed', name='content_status_enum'),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::content_status_enum"))
    op.drop_constraint(op.f('content_items_approval_batch_id_fkey'), 'content_items', type_='foreignkey')
    op.drop_constraint(op.f('content_items_brand_profile_id_fkey'), 'content_items', type_='foreignkey')
    op.create_foreign_key(None, 'content_items', 'brand_profiles', ['brand_id'], ['id'])
    op.drop_column('content_items', 'error_message')
    op.drop_column('content_items', 'asset_path')
    op.drop_column('content_items', 'brand_profile_id')
    op.drop_column('content_items', 'generated_text')
    op.drop_column('content_items', 'approval_batch_id')
    op.add_column('topics', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('topics', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'status')
    op.drop_column('topics', 'source')
    op.add_column('content_items', sa.Column('approval_batch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('content_items', sa.Column('generated_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('content_items', sa.Column('brand_profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('content_items', sa.Column('asset_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('content_items', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.create_foreign_key(op.f('content_items_brand_profile_id_fkey'), 'content_items', 'brand_profiles', ['brand_profile_id'], ['id'])
    op.create_foreign_key(op.f('content_items_approval_batch_id_fkey'), 'content_items', 'approval_batches', ['approval_batch_id'], ['id'])
    op.alter_column('content_items', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('draft', 'generated', 'pending_approval', 'approved', 'scheduled', 'published', 'failed', name='content_status_enum'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::content_status_enum"))
    op.alter_column('content_items', 'content_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('text', 'image', 'reel', 'carousel', name='content_type_enum'),
               existing_nullable=False)
    op.alter_column('content_items', 'platform',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('linkedin', 'instagram', 'facebook', name='platform_enum'),
               existing_nullable=False)
    op.alter_column('content_items', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('content_items', 'created_at')
    op.drop_column('content_items', 'content_text')
    op.drop_column('content_items', 'brand_id')
    op.alter_column('brand_profiles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('brand_profiles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('approval_batches', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('prompt_performance_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], name=op.f('prompt_performance_logs_brand_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('prompt_performance_logs_client_id_fkey')),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt_templates.id'], name=op.f('prompt_performance_logs_prompt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_performance_logs_pkey'))
    )
    op.create_index(op.f('ix_prompt_performance_logs_id'), 'prompt_performance_logs', ['id'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('step', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('logs_pkey'))
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('linkedin_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('linkedin_tokens_pkey'))
    )
    op.create_table('generated_contents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('posted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('prompt_version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], name=op.f('generated_contents_brand_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('generated_contents_client_id_fkey')),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('generated_contents_topic_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_contents_pkey'))
    )
    op.create_index(op.f('ix_generated_contents_id'), 'generated_contents', ['id'], unique=False)
    op.create_table('engagement_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('impressions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('engagement_logs_pkey'))
    )
    op.create_index(op.f('ix_engagement_logs_id'), 'engagement_logs', ['id'], unique=False)
    op.create_table('brand_mutation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_mutated', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mutation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performance_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_profiles.id'], name=op.f('brand_mutation_logs_brand_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('brand_mutation_logs_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_mutation_logs_pkey'))
    )
    op.create_index(op.f('ix_brand_mutation_logs_id'), 'brand_mutation_logs', ['id'], unique=False)
    # ### end Alembic commands ###
