"""add linkedin token lifecycle fields to brand_profiles

Revision ID: 8d6543da7d62
Revises: f3399b409979
Create Date: 2026-01-29 09:07:06.214658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6543da7d62'
down_revision: Union[str, Sequence[str], None] = 'f3399b409979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_profiles', sa.Column('linkedin_connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('brand_profiles', sa.Column('linkedin_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('brand_profiles', sa.Column('linkedin_disconnected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_profiles', 'linkedin_disconnected_at')
    op.drop_column('brand_profiles', 'linkedin_token_expires_at')
    op.drop_column('brand_profiles', 'linkedin_connected_at')
    # ### end Alembic commands ###
