"""add scheduled_at to linkedin_posts

Revision ID: c6ea06c4ce67
Revises: 8d6543da7d62
Create Date: 2026-01-29 19:31:11.361991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6ea06c4ce67'
down_revision: Union[str, Sequence[str], None] = '8d6543da7d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linkedin_posts', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linkedin_posts', 'scheduled_at')
    # ### end Alembic commands ###
