"""add retry and backoff fields to linkedin_posts

Revision ID: f3399b409979
Revises: a0a249e1c96c
Create Date: 2026-01-28 20:00:24.892629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3399b409979'
down_revision: Union[str, Sequence[str], None] = 'a0a249e1c96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


"""add retry and backoff fields to linkedin_posts

Revision ID: f3399b409979
Revises: a0a249e1c96c
Create Date: 2026-01-28 20:00:24.892629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3399b409979'
down_revision: Union[str, Sequence[str], None] = 'a0a249e1c96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣ Add columns safely (with backfill)
    op.add_column(
        'linkedin_posts',
        sa.Column('error_type', sa.String(length=50), nullable=True)
    )

    op.add_column(
        'linkedin_posts',
        sa.Column(
            'retry_count',
            sa.Integer(),
            nullable=False,
            server_default="0",  # 🔑 critical
        )
    )

    op.add_column(
        'linkedin_posts',
        sa.Column(
            'next_retry_at',
            sa.DateTime(timezone=True),
            nullable=True
        )
    )

    # 2️⃣ Existing schema adjustments (safe)
    op.alter_column(
        'linkedin_posts',
        'linkedin_post_urn',
        existing_type=sa.VARCHAR(length=255),
        nullable=True
    )

    op.alter_column(
        'linkedin_posts',
        'published_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text('now()')
    )

    op.drop_constraint(
        op.f('linkedin_posts_linkedin_post_urn_key'),
        'linkedin_posts',
        type_='unique'
    )

    # 3️⃣ Remove server default (keep DB clean)
    op.alter_column(
        'linkedin_posts',
        'retry_count',
        server_default=None,
    )




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('linkedin_posts_linkedin_post_urn_key'), 'linkedin_posts', ['linkedin_post_urn'], postgresql_nulls_not_distinct=False)
    op.alter_column('linkedin_posts', 'published_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('linkedin_posts', 'linkedin_post_urn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('linkedin_posts', 'next_retry_at')
    op.drop_column('linkedin_posts', 'retry_count')
    op.drop_column('linkedin_posts', 'error_type')
    # ### end Alembic commands ###
